
package com.mycompany.finaltopicos;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author david
 */
public class VentanaAyuda extends javax.swing.JFrame {


    public VentanaAyuda() {
        initComponents();
        label_Ayuda.setIcon(ajustarImage("/imagenes/ayuda.png", label_Ayuda));
        label_example.setIcon(ajustarImage("/imagenes/exampleAyuda.png", label_example));
        imgMultiplicacion.setIcon(ajustarImage("/imagenes/mult.png", imgMultiplicacion));
        imgIgual.setIcon(ajustarImage("/imagenes/igual.png", imgIgual));
        back.setIcon(ajustarImage("/imagenes/back.png", back));
    }
        public Icon ajustarImage(String direccion, JLabel boton){
        ImageIcon icono = new ImageIcon(getClass().getResource(direccion));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon img = new ImageIcon(icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label_Ayuda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textEstatico = new javax.swing.JTextField();
        imgMultiplicacion = new javax.swing.JLabel();
        textAleatorio = new javax.swing.JTextField();
        imgIgual = new javax.swing.JLabel();
        textResultado = new javax.swing.JTextField();
        label_example = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(59, 43, 70));
        setMaximumSize(new java.awt.Dimension(1116, 800));
        setMinimumSize(new java.awt.Dimension(1116, 800));
        setPreferredSize(new java.awt.Dimension(1116, 800));

        jPanel1.setBackground(new java.awt.Color(59, 43, 70));
        jPanel1.setMaximumSize(new java.awt.Dimension(1116, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1116, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1116, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(66, 78, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Comó multiplicar?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(label_Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_Ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1116, 80));

        textEstatico.setEditable(false);
        textEstatico.setBackground(new java.awt.Color(255, 165, 0));
        textEstatico.setFont(new java.awt.Font("MS UI Gothic", 1, 130)); // NOI18N
        textEstatico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textEstatico.setText("3");
        textEstatico.setBorder(null);
        textEstatico.setPreferredSize(new java.awt.Dimension(276, 257));
        textEstatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEstaticoActionPerformed(evt);
            }
        });
        jPanel1.add(textEstatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, 140));
        jPanel1.add(imgMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 80, 80));

        textAleatorio.setEditable(false);
        textAleatorio.setBackground(new java.awt.Color(255, 165, 0));
        textAleatorio.setFont(new java.awt.Font("MS UI Gothic", 1, 130)); // NOI18N
        textAleatorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textAleatorio.setText("4");
        textAleatorio.setBorder(null);
        textAleatorio.setPreferredSize(new java.awt.Dimension(276, 257));
        textAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAleatorioActionPerformed(evt);
            }
        });
        jPanel1.add(textAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 130, 140));
        jPanel1.add(imgIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 80, 80));

        textResultado.setEditable(false);
        textResultado.setBackground(new java.awt.Color(255, 165, 0));
        textResultado.setFont(new java.awt.Font("MS UI Gothic", 1, 130)); // NOI18N
        textResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textResultado.setText("12");
        textResultado.setBorder(null);
        textResultado.setPreferredSize(new java.awt.Dimension(276, 257));
        jPanel1.add(textResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 140, 140));

        label_example.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                label_exampleAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(label_example, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 904, 390));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Es lo mismo que lo siguiente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 904, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Una multiplicación es una suma repetitiva, por ejemplo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 904, -1));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 620, 80, 80));

        jPanel3.setBackground(new java.awt.Color(66, 78, 94));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textEstaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEstaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEstaticoActionPerformed

    private void textAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAleatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAleatorioActionPerformed

    private void label_exampleAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_label_exampleAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_label_exampleAncestorAdded

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
   this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAyuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel imgIgual;
    private javax.swing.JLabel imgMultiplicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_Ayuda;
    private javax.swing.JLabel label_example;
    private javax.swing.JTextField textAleatorio;
    private javax.swing.JTextField textEstatico;
    private javax.swing.JTextField textResultado;
    // End of variables declaration//GEN-END:variables
}
